# Learning Numpy

In [36]:
import numpy as np 

### Creating Arrays

<strong><ins>All arrays mentioned here are numpy arrays as long as opposite is not mentioned</ins></strong> please solve the problems with this knowledge.

Create an array in size of 4*3 and assing it to arr variable 

In [37]:
arr = np.array((4,3))

Create an array with elements from 0 to 15 (both inclusive) and assing it to arr2 variable   
Then print the shape of the arr2  
copy the arr2 to arr2_copy  
print arr2, arr2_copy   
Change its shape to 4*4 and assign to itself   
print arr2, arr2_copy again    

In [38]:
arr2 = np.arange(16)

In [39]:
print(arr2.shape)

(16,)


In [40]:
arr2_copy = arr2.copy()

In [41]:
print(arr2, arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [42]:
arr2_copy = arr2_copy.reshape((4,4))

In [43]:
print(arr2, arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Some Functions 

##### How many dimenions there are in arr2 variable? 

In [44]:
arr2.ndim

1

##### Describe the number of rows and columns in arr2 variable 

In [45]:
arr2.shape

(16,)

##### How many elements there are in arr2 variable?

In [46]:
arr2.size

16

##### Print the data type of arr2

In [47]:
arr2.dtype

dtype('int32')

#### Print the data location in the memory

In [48]:
id(arr2)

2143548788048

### Some Statistics About the Arrays

#### Show 50th percentile of arr2

In [49]:
np.quantile(arr2, 0.5)

7.5

#### Show mean of arr2 elements

In [50]:
np.mean(arr2)

7.5

#### Show median of arr2 elements

In [51]:
np.median(arr2)

7.5

##### Create one dimensional normally distrubuted array with mean 3 standard deviation is 4 and has elements of 100

In [52]:
from numpy import random

In [53]:
s = np.random.normal(loc = 3,scale = 4, size = 100)

#### Install matplotlib library for ploting purposes and then plot the s 
- search to find how to do

In [54]:
import matplotlib.pyplot as plt
fig , ax = plt.subplots()

ax.hist(s)
plt.show()

____

# Learning Pandas

##### Read the airline safety data assign to df variable and print first 5 rows with pandas function

In [55]:
import pandas as pd 

In [56]:
df = pd.read_csv("C:/Users/KORKMAZ/Desktop/DEVELHOPE/EXERCISES PANDAS-NUMPY/airline_safety_data.txt")

In [57]:
df.head()

airline  avail_seat_km_per_week  incidents_85_99  \
0             Aer Lingus               320906734                2   
1              Aeroflot*              1197672318               76   
2  Aerolineas Argentinas               385803648                6   
3            Aeromexico*               596871813                3   
4             Air Canada              1865253802                2   

   fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
0                      0                 0                0   
1                     14               128                6   
2                      0                 0                1   
3                      1                64                5   
4                      0                 0                2   

   fatal_accidents_00_14  fatalities_00_14  
0                      0                 0  
1                      1                88  
2                      0                 0  
3                      0                 0  
4                      0                 0

##### print last 5 rows with pandas function

In [58]:
df.tail()

airline  avail_seat_km_per_week  incidents_85_99  \
51       United / Continental*              7139291291               19   
52  US Airways / America West*              2455687887               16   
53            Vietnam Airlines               625084918                7   
54             Virgin Atlantic              1005248585                1   
55             Xiamen Airlines               430462962                9   

    fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
51                      8               319               14   
52                      7               224               11   
53                      3               171                1   
54                      0                 0                0   
55                      1                82                2   

    fatal_accidents_00_14  fatalities_00_14  
51                      2               109  
52                      2                23  
53                      0                 0  
54                      0                 0  
55                      0                 0

##### Show shape of df

In [59]:
df.shape

(56, 8)

##### Show descriptive statistics of df

In [60]:
df.describe()

avail_seat_km_per_week  incidents_85_99  fatal_accidents_85_99  \
count            5.600000e+01        56.000000              56.000000   
mean             1.384621e+09         7.178571               2.178571   
std              1.465317e+09        11.035656               2.861069   
min              2.593733e+08         0.000000               0.000000   
25%              4.740362e+08         2.000000               0.000000   
50%              8.029089e+08         4.000000               1.000000   
75%              1.847239e+09         8.000000               3.000000   
max              7.139291e+09        76.000000              14.000000   

       fatalities_85_99  incidents_00_14  fatal_accidents_00_14  \
count         56.000000        56.000000              56.000000   
mean         112.410714         4.125000               0.660714   
std          146.691114         4.544977               0.858684   
min            0.000000         0.000000               0.000000   
25%            0.000000         1.000000               0.000000   
50%           48.500000         3.000000               0.000000   
75%          184.250000         5.250000               1.000000   
max          535.000000        24.000000               3.000000   

       fatalities_00_14  
count         56.000000  
mean          55.517857  
std          111.332751  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           83.250000  
max          537.000000

#### Show df column informations

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   airline                 56 non-null     object
 1   avail_seat_km_per_week  56 non-null     int64 
 2   incidents_85_99         56 non-null     int64 
 3   fatal_accidents_85_99   56 non-null     int64 
 4   fatalities_85_99        56 non-null     int64 
 5   incidents_00_14         56 non-null     int64 
 6   fatal_accidents_00_14   56 non-null     int64 
 7   fatalities_00_14        56 non-null     int64 
dtypes: int64(7), object(1)
memory usage: 3.6+ KB


#### Select companies and incidents_85_99 with incidents_85_99 is less than 10

In [62]:
df[df["incidents_85_99"] < 10][["airline","incidents_85_99"]].sort_values("incidents_85_99", ascending = False)

airline  incidents_85_99
55         Xiamen Airlines                9
20                Egyptair                8
50        Turkish Airlines                8
49            Thai Airways                8
47                     TAM                8
35  Pakistan International                8
53        Vietnam Airlines                7
40           Saudi Arabian                7
36     Philippine Airlines                7
30                    KLM*                7
9                 Alitalia                7
2    Aerolineas Argentinas                6
33              Lufthansa*                6
8         Alaska Airlines*                5
39                    SAS*                5
38         Royal Air Maroc                5
13                 Avianca                5
27                  Iberia                4
14        British Airways*                4
3              Aeromexico*                3
28          Japan Airlines                3
32            LAN Airlines                3
7         Air New Zealand*                3
34       Malaysia Airlines                3
10      All Nippon Airways                3
46                    TACA                3
18                    COPA                3
17                  Condor                2
42           South African                2
4               Air Canada                2
6               Air India*                2
45                  SWISS*                2
44   Sri Lankan / AirLanka                2
0               Aer Lingus                2
41      Singapore Airlines                2
29           Kenya Airways                2
43      Southwest Airlines                1
25                Gulf Air                1
37                 Qantas*                1
12       Austrian Airlines                1
21                   El Al                1
54         Virgin Atlantic                1
23                 Finnair                1
15         Cathay Pacific*                0
48      TAP - Air Portugal                0
26       Hawaiian Airlines                0

#### Group companies by first letter(lower) and take the mean incidents_85_99 and make it a dataframe again 

In [91]:
df['l_airline'] = df['airline'].str.lower()
new_df = pd.DataFrame(df.groupby(df["l_airline"].str[0])["incidents_85_99"].mean())

In [92]:
new_df

incidents_85_99
l_airline                 
a                10.714286
b                 4.000000
c                 4.250000
d                24.000000
e                11.333333
f                 1.000000
g                 5.500000
h                 0.000000
i                 4.000000
j                 3.000000
k                 7.000000
l                 4.500000
m                 3.000000
p                 7.500000
q                 1.000000
r                 5.000000
s                 3.000000
t                 5.400000
u                17.500000
v                 4.000000
x                 9.000000